// This file has been generated by Tauri Specta. Do not edit this file manually.

import type * as pomme_launcher$auth from "./pomme_launcher/auth";
import type * as pomme_launcher$commands from "./pomme_launcher/commands";
import type * as pomme_launcher$downloader from "./pomme_launcher/downloader";
import type * as pomme_launcher$friends from "./pomme_launcher/friends";
import type * as pomme_launcher$installations from "./pomme_launcher/installations";
import type * as pomme_launcher$ping from "./pomme_launcher/ping";
import type * as pomme_launcher$settings from "./pomme_launcher/settings";

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAllAccounts: () => __TAURI_INVOKE<pomme_launcher$auth.AuthAccount[]>("get_all_accounts"),
	addAccount: () => typedError<pomme_launcher$auth.AuthAccount, string>(__TAURI_INVOKE("add_account")),
	removeAccount: (uuid: string) => __TAURI_INVOKE<void>("remove_account", { uuid }),
	ensureAssets: (version: string) => typedError<null, string>(__TAURI_INVOKE("ensure_assets", { version })),
	getVersions: (showSnapshots: boolean | null) => typedError<pomme_launcher$commands.GameVersion[], string>(__TAURI_INVOKE("get_versions", { showSnapshots })),
	refreshAccount: (uuid: string) => typedError<pomme_launcher$auth.AuthAccount, string>(__TAURI_INVOKE("refresh_account", { uuid })),
	getSkinUrl: (uuid: string) => typedError<string, string>(__TAURI_INVOKE("get_skin_url", { uuid })),
	getPatchNotes: (count: number | null) => typedError<pomme_launcher$commands.PatchNote[], string>(__TAURI_INVOKE("get_patch_notes", { count })),
	getPatchContent: (contentPath: string) => typedError<string, string>(__TAURI_INVOKE("get_patch_content", { contentPath })),
	launchGame: (installId: string, uuid: string | null, serverIp: string | null, overrideVersion: string | null, debugEnabled: boolean | null) => typedError<string, string>(__TAURI_INVOKE("launch_game", { installId, uuid, serverIp, overrideVersion, debugEnabled })),
	getClientLogs: () => typedError<string[], null>(__TAURI_INVOKE("get_client_logs")),
	loadLauncherSettings: () => __TAURI_INVOKE<pomme_launcher$settings.LauncherSettings>("load_launcher_settings"),
	setLauncherLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_launcher_language", { language })),
	setKeepLauncherOpen: (keep: boolean) => typedError<null, string>(__TAURI_INVOKE("set_keep_launcher_open", { keep })),
	setLaunchWithConsole: (launch: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_with_console", { launch })),
	pingServer: (address: string) => __TAURI_INVOKE<pomme_launcher$ping.ServerStatus>("ping_server", { address }),
	loadServers: () => __TAURI_INVOKE<pomme_launcher$ping.SavedServer[]>("load_servers"),
	saveServers: (servers: pomme_launcher$ping.SavedServer[]) => typedError<null, string>(__TAURI_INVOKE("save_servers", { servers })),
	loadInstallations: () => typedError<pomme_launcher$installations.Installation[], pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("load_installations")),
	createInstallation: (payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("create_installation", { payload })),
	deleteInstallation: (id: string) => typedError<null, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("delete_installation", { id })),
	duplicateInstallation: (oldId: string, payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("duplicate_installation", { oldId, payload })),
	editInstallation: (id: string, payload: pomme_launcher$installations.InstallationDraft) => typedError<pomme_launcher$installations.Installation, pomme_launcher$installations.InstallationError>(__TAURI_INVOKE("edit_installation", { id, payload })),
	getDownloadedVersions: () => __TAURI_INVOKE<string[]>("get_downloaded_versions"),
	getFriends: (uuid: string) => typedError<pomme_launcher$friends.FriendsList, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("get_friends", { uuid })),
	sendFriendRequest: (uuid: string, name: string) => typedError<pomme_launcher$friends.FriendsList, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("send_friend_request", { uuid, name })),
	acceptFriendRequest: (uuid: string, friendUuid: string) => typedError<pomme_launcher$friends.FriendsList, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("accept_friend_request", { uuid, friendUuid })),
	removeFriend: (uuid: string, friendUuid: string) => typedError<pomme_launcher$friends.FriendsList, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("remove_friend", { uuid, friendUuid })),
	updatePresence: (uuid: string, status: string, joinInfo: {
	value: string,
	invited: boolean,
} | null) => typedError<pomme_launcher$friends.PresenceEntry[], pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("update_presence", { uuid, status, joinInfo })),
	getFriendSettings: (uuid: string) => typedError<pomme_launcher$friends.FriendSettings, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("get_friend_settings", { uuid })),
	updateFriendSettings: (uuid: string, showInList: boolean, acceptInvites: boolean) => typedError<pomme_launcher$friends.FriendSettings, pomme_launcher$friends.FriendsApiError>(__TAURI_INVOKE("update_friend_settings", { uuid, showInList, acceptInvites })),
};

/** Events */
export const events = {
	consoleMessageEvent: makeEvent<pomme_launcher$commands.ConsoleMessageEvent>("console-message-event"),
	downloadProgressEvent: makeEvent<pomme_launcher$downloader.DownloadProgressEvent>("download-progress-event"),
	gameExitedEvent: makeEvent<pomme_launcher$commands.GameExitedEvent>("game-exited-event"),
};

/* Tauri Specta runtime */
export type Result<T, E> =
  | { ok: true;  value: T }
  | { ok: false; error: E };

export const Result = {
  ok<T>(value: T): Result<T, never> {
    return { ok: true, value };
  },
  err<E>(error: E): Result<never, E> {
    return { ok: false, error };
  },
} as const;


export async function typedError<T, E>(promise: Promise<T>): Promise<Result<T, E>> {
  try {
    return Result.ok(await promise);
  } catch (e) {
    if (e instanceof Error) throw e;
    return Result.err(e as E);
  }
}

const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}
